### ISSUE TITLE
Integrate RDS writing

### ISSUE THREAD

**Issue by bethac07** [DistributedScience/Distributed-CellProfiler#10]

**Comment by ErinWeisbart** [comment]
Rather than the way CP currently uses ExportToSpreadsheet or ExportToDatabase, RDS is a centrally hosted database that could be written to.
This setup needs to happen within CellProfiler before making changes to DCP (and might not require actual DCP changes).
Moving this issue to CellProfiler (not Distributed-CellProfiler).
Can be re-opened if changes are made to CP and require changes to DCP.
