### ISSUE TITLE
ECS issue : No Container Instances were found in your cluster.

### ISSUE THREAD

**Issue by nicolasboisseau** [DistributedScience/Distributed-CellProfiler#126]
Hello!

I'm following the instructions in order to setup DCP on AWS.  The setup and submit job steps are working fine but when i launch the run startCluster command, even if the spotfleet seems to start properly, nothing happens. The EC2 are up, but ECS Service cannot go forward.

ECS event message is : "service DistributedJumpCPService was unable to place a task because no container instance met all of its requirements. Reason: No Container Instances were found in your cluster."

I realized that the DOCKERHUB_TAG i put in the config file is not enough for ECS to put the docker on EC2.

I'm not an expert in ECS but i understood that we must register the image in ECR first? is it what you recommand ? As I did not see any reference to this in the installation procedure I wanted to inform you about this to maybe add some details ?

I work in an environment where spotfleet instances cannot have an external IP and then the spotfleet template is not completely applicable. Do you think it can be a problem for the execution of the next steps ?

Many thanks for your clarifications

**Comment by bethac07** [comment]
1) Are your machines making it into your ECS cluster within ~5 minutes of them being started in the spot fleet?
2) Have you made sure to match your container specifications to your machine type?
3) The Dockerhub tag SHOULD be sufficient for Dockers to be placed onto machines, assuming 1 and 2 are both yes's, no need to do any other steps like registering your container into the ECR.

**Comment by nicolasboisseau** [comment]
Thank you for your hints. It's definitely the point 1 that is the problem. I managed to use a spotfleet template similar to the one you provided but the EC2 machines are not discovered by the ECS cluster. I will continue to investigate and review again the AMI roles setup and also if there are not enterprise security policies that govern the aws account i use.

**Comment by mamrrmam** [comment]
Hi, has there been any resolution to this issue? I am currently experiencing the same problem. I have an additional problem of running into spot fleet count limits on the machines that I need, but when I have configured the config.py and fleet.json files to run smaller instances they never register with ECS. Everything seems to run fine but the instances don't get tagged into the service running my job.

**Comment by nicolasboisseau** [comment]
Hi. On my side not really. We decided to work without distributed cell profiler for now. When i investigated with the cloud architect, they confirmed to me that as we are in an enterprise managed configuration, an external security layer was operating outside the aws account and blocking everything by default (e.g. on EC2 instances). Perhaps you are in the same situation ?

**Comment by ErinWeisbart** [comment]
I'm going to close this for now because we don't have enough information to replicate your situation.

We have this problem mentioned in our [Troubleshooting documentation](https://distributedscience.github.io/Distributed-CellProfiler/troubleshooting_runs.html). In our hands, we encounter this problem in three situations:

1) **There is a mismatch in the DCP config file.** This happens particularly when MEMORY does not match the MACHINE_TYPE set in the config. If the memory is set larger than the machine, ECS will fail to place dockers. You may find error information in the AWS console in ECS => Clusters => YOUR_CLUSTER => Services => YOUR_SERVICE => Deployments

2) **The docker doesn't exist in docker hub.** Confirm that there are no typos in your DOCKERHUB_TAG set in your config.

3) **Permissions aren't set up correctly.** Check that you have set up permissions correctly for the user or role that you have set in your config under AWS_PROFILE. We have since introduced [`setup_aws.py`](https://github.com/DistributedScience/Distributed-CellProfiler/blob/master/setup_AWS.py) which will automatically generate sufficient roles for you to help mitigate this. More information is available in [our setup documentation](https://distributedscience.github.io/Distributed-CellProfiler/step_0_prep.html).
