### ISSUE TITLE
CP PROBLEM: Done file reports failure

### ISSUE THREAD

**Issue by znavidi** [DistributedScience/Distributed-CellProfiler#180]
Hi,

I am facing the **CP PROBLEM: Done file reports failure** error when running a distributed cellprofiler pipeline on AWS, with error details provided below. None of the output folders specified in the job.json file are created, and I am not sure why it says "**MyExpt_Per_Image table already in database and overwrite not allowed. Exiting**". I have not found any solution or hint to address this issue from previous questions, and would appreciate any guidance.

<img width="1231" alt="Screenshot 2024-08-25 at 7 58 54 PM" src="https://github.com/user-attachments/assets/2218a1f4-5f7c-41df-9ffb-86b3f381b197">

Thanks in advance

**Comment by emiglietta** [comment]
Hi @znavidi !

This error is likely due to the fact the the ExportToDatabase module has the "Overwrite without warning?" set ti "Never"

![image](https://github.com/user-attachments/assets/5b9aa773-d56d-4624-86e0-30d4b801151e)

Or, in the code:

<img width="388" alt="image" src="https://github.com/user-attachments/assets/118a2dae-e146-487b-99e0-37ae48164c0a">

See also a [similar issue](https://forum.image.sc/t/adjusting-preparing-in-out-folder-while-creating-the-pipeline-for-batch-processing/51862/5?u=esteban_miglietta) reported on the image.sc forum

**Comment by ErinWeisbart** [comment]
@emiglietta Can you add this to the [Distributed-CellProfiler troubleshooting rubric](https://distributedscience.github.io/Distributed-CellProfiler/troubleshooting_runs.html)?

**Comment by znavidi** [comment]
Thanks so much @emiglietta! That helped figuring out the issue and resolving it!

**Comment by ErinWeisbart** [comment]
added to docs with https://github.com/DistributedScience/Distributed-CellProfiler/commit/e2fda310f908788b86384a32e030b3312132f385
