### ISSUE TITLE
Add support for file lists

### ISSUE THREAD

**Issue by bethac07** [DistributedScience/Distributed-CellProfiler#23]

**Comment by ErinWeisbart** [comment]
I'd like to add this, but I've never personally used file lists and I'm having a hard time finding much info about them in our documentation.

It says in our [command line blog post](https://carpenter-singh-lab.broadinstitute.org/blog/getting-started-using-cellprofiler-command-line) that file lists can be passed using `--file-list` as the input component. And our [Adapting CP to LIMS](https://github.com/CellProfiler/CellProfiler/wiki/Adapting-CellProfiler-to-a-LIMS-environment) suggests that CP will load all the files in the list in place of whatever is set in the `Images` module of the pipeline.

Wondering if we can we assume file lists are always .txt files? I think [here](https://github.com/CellProfiler/core/blob/bc67be021879ccebc3bba8ac76136b7503a28fe3/cellprofiler_core/pipeline/_pipeline.py#L2053) is where they are being loaded into CellProfiler and it just requires UTF8 which doesn't necessarily mean .txt if I'm understanding it correctly.

I'm asking because currently in DCP it handles two file methods [here](https://github.com/DistributedScience/Distributed-CellProfiler/blob/9917a0669cdde4120dde345188741cf58cb59bde/worker/cp-worker.py#L227): Batch Files and LoadData.csv. If it receives an .h5 (batch file) then it makes the command 1 way, if it doesn't then it passes --data-file. 
To make it support 3 types, I'm wondering what else we should have it parse on: 
- if it IS `.csv` then it's `--data-file`, else `--file-list`
- if it is NOT `.csv` then it's `--file-list`, else `--data-file`
- if it IS `.txt` then it's `--file-list`, else `--data-file`
- if it is NOT `.txt` then it's `--data-file`, else `--file-list`
- if it IS `.csv` then it's `--data-file`, if it IS `.txt` then it's `--file-list`, else `ERROR`
- another approach...?

**Comment by bethac07** [comment]
Thanks for thinking about this deeply! I'd say that we can at least start by assuming they will always be .txt files - if someone brings us a compelling corner case later for supporting non-.txt files, happy to hear them out and see what we can do at that point. I think at that point, what might be easiest would be to have the extensions supported by each "path" (CSV, file list, or batch file; there's also a 4th path we could consider supporting, which is "none of the above and just using -i at the command line", but I don't think it's necessarily a good idea for folks to do that so my feeling at this way is to intentionally not-support it) as a list; that way you could do something like 

```
batch_file_extensions = ['.h5']
file_list_extensions = ['.txt']
if input_file_extension in batch_file_extensions:
    # code for making command parts for batch_files
elif input_file_extension in file_list_extensions:
    # code for making command parts for file lists
else:
    # code for making command parts for load data
```

**Comment by ErinWeisbart** [comment]
Drafted in https://github.com/DistributedScience/Distributed-CellProfiler/pull/142/commits/b265f43e63eb97d34dbb5d391bc03495883583c0. (Needs to be tested)

**Comment by ErinWeisbart** [comment]
@bethac07 did you envision DCP downloading the file list and parsing it into individual jobs? or do we just say if you are passing a file list then there is no grouping because there is no metadata to group on and therefore only one job?

**Comment by ErinWeisbart** [comment]
I've tested the file list command and it works to take in the file list and run without grouping. Will need to either a) add to documentation that you can't actually distribute with file lists or b) update DCP further to allow grouping and file lists.

**Comment by bethac07** [comment]
Metadata that is extracted/can be extracted from the file and folder names (or in theory by a CSV if you've added an external one, though I haven't rigorously tested that) can definitely been used to run grouping-based pipelines. Here I've updated AdvancedSegmentation to a) take a file list and b) group by well, and you can see it runs fine- this pipeline has 2 images per well, if I give it the first well, it runs just the first 2 images, if it's given the 4th well to run, it starts from image 7. So really it's just recognizing the flag and passing it just like anything else, as well as adding the documentation. 

<img width="1298" alt="image" src="https://user-images.githubusercontent.com/6721515/214084297-ca34f19e-ea5b-4ac6-a7f8-825b4d2a523c.png">

**Comment by bethac07** [comment]
Looks like grouping on external metadata works fine too, as long as CellProfiler is set to look for it in the "Default Input Folder" and we specify the Default Input Folder[^1] (note the extra `-i` compared to above).

[^1]: [We already do this for the other sets of commands](https://github.com/DistributedScience/Distributed-CellProfiler/blob/master/worker/cp-worker.py#L246-L250)

<img width="1420" alt="image" src="https://user-images.githubusercontent.com/6721515/214086236-f2a7381a-1e00-4c82-86de-bbff36503995.png">

**Comment by ErinWeisbart** [comment]
So is it correct to say:

Note that file lists themselves do not associate metadata with file paths (in contrast to LoadData.csv files where you can enter any metadata columns you desire.)
Therefore, you need to extract metadata for Distributed-CellProfiler to use for grouping by either 1) extracting metadata from file and folder names in the Metadata module in your CellProfiler pipeline or 2) setting the Metadata module in CellProfiler to `Import from file` and setting Metadata file location to `Default Input Folder` .

And then the DCP run command (that works with either option) is
`cmd = f'cellprofiler -c -r -p {DATA_ROOT}/{message["pipeline"]} -i {DATA_ROOT}/{message["input"]} -o {localOut} -d {cpDone} --file-list={data_file_path} -g {message["Metadata"]}'`

**Comment by bethac07** [comment]
Even to import from file, you need some metadata to associate with, so 1 always, 2 optional. This is the same as for batch files, identically.

**Comment by ErinWeisbart** [comment]
You're saying that you always have to extract from file/folder names but can add additional metadata with external file? So is this correct?:

Therefore, you need to extract metadata for Distributed-CellProfiler to use for grouping by extracting metadata from file and folder names in the Metadata module in your CellProfiler pipeline. You can pass additional metadata to CellProfiler by  `Add another extraction method`, setting the method to `Import from file` and setting Metadata file location to Default Input Folder .
